[build]
  publish = "out"  # Acesta poate fi diferit în funcție de setup-ul tău Next.js, dacă folosești o altă locație
  command = "npm run build"

[[build.environment]]
  NODE_ENV = "production"

[[build.cache]]
  paths = ["node_modules", ".next/cache"]
