[build]
  environment = { NODE_ENV = "production" }
  publish = "out"  # Sau directorul unde Next.js generează build-ul
  command = "npm run build"
  cache = ["node_modules", ".next/cache"]
[[plugins]]
  package = "@netlify/plugin-nextjs"
